// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCN4TCbh4Q-cIQK68urX1LVKhNSG0gDe_U',
    appId: '1:638849289790:web:12fadf2c83d3487c1acb6f',
    messagingSenderId: '638849289790',
    projectId: 'mobile-4ebd7',
    authDomain: 'mobile-4ebd7.firebaseapp.com',
    storageBucket: 'mobile-4ebd7.appspot.com',
    measurementId: 'G-PPTPTPHJWC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC-y468yRAZu29tQEFuR9ft12O9lwGiQwE',
    appId: '1:638849289790:android:15972ff7463055ac1acb6f',
    messagingSenderId: '638849289790',
    projectId: 'mobile-4ebd7',
    storageBucket: 'mobile-4ebd7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8lYT0BYdMJ9PyL4I8Kt_ZE1spuC41mQM',
    appId: '1:638849289790:ios:95b85ebf924848b91acb6f',
    messagingSenderId: '638849289790',
    projectId: 'mobile-4ebd7',
    storageBucket: 'mobile-4ebd7.appspot.com',
    iosBundleId: 'com.example.mobileAkhir',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8lYT0BYdMJ9PyL4I8Kt_ZE1spuC41mQM',
    appId: '1:638849289790:ios:274d75437d8e58661acb6f',
    messagingSenderId: '638849289790',
    projectId: 'mobile-4ebd7',
    storageBucket: 'mobile-4ebd7.appspot.com',
    iosBundleId: 'com.example.mobileAkhir.RunnerTests',
  );
}
